[workspace]
members = ["projects/*"]
default-members = [
    "projects/safe-tensors-export",
]
exclude = [
    "projects/.DS_Store",
    "projects/tensorflow",
    "projects/onnx"
]

[profile.release]
lto = true
panic = "abort"
